name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: Semver version to bump
        options:
          - patch
          - minor
          - major
        default: patch
      dry-run:
        type: boolean
        description: Perform dry-run
        default: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    name: build dist
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: main

      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - uses: chainguard-dev/actions/setup-gitsign@5478b1fb59c858e26e88f3564e196f1637e6d718
      - name: Set up Git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: |
          pnpm i
          npm run build

      - name: release
        run: npm run release ${{ github.event.inputs.bump }}${{ github.event.inputs.dry-run == 'true' && ' -- --dry-run' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
